version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=build-$CODEBUILD_BUILD_NUMBER
      - ECR_REGISTRY=$(echo $REPOSITORY_URI | cut -d'/' -f1)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed on $(date)"
      - echo Image pushed as $IMAGE_TAG